version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  mynetwork:



#docker-compose up -d --build
#crating database user
#docker exec -it mysql-db mysql -u root -p
CREATE DATABASE mydatabase;
CREATE USER 'myuser'@'%' IDENTIFIED BY 'mypassword';
GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser'@'%';
FLUSH PRIVILEGES;
EXIT;

